[build]
builder = "nixpacks"
buildCommand = "python -m pip install -r worker/crawler/requirements.txt"

[deploy]
startCommand = "python worker/crawler/run.py"
cronSchedule = "0 13 * * *"
restartPolicyType = "never"
